### ISSUE TITLE
Feature: Jetson nano generating sensor data

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#1]
### Description
As a user, I'd like to be able to fetch the latest sensor data of the Jetson nano, in order to be kept up to date of the data in my room.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be callable by rest API for testing
- [x] Should publish a message to the rabbitmq for each sensor data update

Also, here are a few points that need to be addressed:

1. Constraint 1: The temperature has to be in degrees celsius not in freedom units.

### Tasks
- [x] Set up the Jetson nano in my room
- [x] Create the python script
- [x] Create docker container
