### ISSUE TITLE
Feature: UpdateRoom

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#10]
### Description
As a hap-user, I'd like to edit a room, so I can keep all rooms up to date on the dashboard.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should convert room name to an input on click
- [ ] Should update database on entering the updated room name

### Tasks
- [ ] _TBA_ Create a database query to edit rooms by id
- [ ] _TBA_ Create a PUT endpoint to edit a room by using the edit query
- [ ] _TBA_ Toggle room name to an input on click
- [ ] _TBA_ Call the PUT endpoint when updated room name is filled onEnter
