### ISSUE TITLE
Feature: DeleteRoom

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#11]
### Description
As a hap-user, I'd like to delete a room to the dashboard, so I can keep the dashboard up to date with my rooms.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should delete room on button "delete" click

### Tasks
- [x] _TBA_ Create a database query to delete a room by id
- [x] _TBA_ Create a DELETE endpoint to delete a room by using the delete query
- [ ] _TBA_ Add delete button that calls the DELETE endpoint on click
