### ISSUE TITLE
[Feature #6]: ShowMeasurementsInChart

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#12]
### Description
As a Hap-user, I'd like to see sensor data daily from the selected room in a chart, in order to show the behavior of the data.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should show all the measurements in a chart.

### Tasks
- [x] Front end should call "GetAllMeasurementsByRoomName " endpoint for retrieving the sensor data.
- [x] Should be represented in a Chart categorized on Sensor-measurements.

**Comment by SiemLuc** [comment]
Sometimes when returning the brightness (in Lux) somehow mutates (or bitshifts?) to 65280 or 65535. 

Here's there code provided for obtaining the brightness from my Sensorhub mounted on the Jetson Nano.

```py def get_brightness(self):
        light_reg_l = self.bus.read_byte_data(self.DEVICE_ADDR, self.LIGHT_REG_L)
        light_reg_h = self.bus.read_byte_data(self.DEVICE_ADDR, self.LIGHT_REG_H)
        print(bin(light_reg_h << 8 | light_reg_l))
        return str(light_reg_h << 8 | light_reg_l)```
        
Keep in mind that I am still a newbie when it comes to python or bit-operators, so feedback would be much appreciated!
