### ISSUE TITLE
Feature: GetAllMeasurementsByRoomName

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#17]
### Description
As a hap-user, I'd like to retrieve all measurements by the given room name, in order to show all the measurements in a chart.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should retrieve all measurements by room name button click/on page load of the dashboard
- [x] Should be tested with unit, integration testing

### Tasks
- [x] _TBA_ Create a GET endpoint to get all measurements by room name
- [x] _TBA_ Create on page load event that fetches all measurements by room
- [x] _TBA_ Create on button click event that fetches all measurements by room
- [x] _TBA_ Test Acceptance Criteria
