### ISSUE TITLE
Feature: Create Dashboard

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#3]
### Description
As a HAP-user, I'd like to view the dashboard, in order to get an overview of the rooms which contains the sensor-data.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to show if lamps are turned on/off
- [x] Should be able to give an overview of the temperature in given room

Also, here are a few points that need to be addressed:

1. Constraint 1: User must be authenticated .

### Tasks
- [x] _TBA_ Create DashboardPage
- [x] _TBA_ Get overview of lamps status
- [x] _TBA_ Get overview of temperature
