### ISSUE TITLE
Feature: Current Spotify song playing

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#34]
### Description
As a HAP-dashboard user, I'd like to know what Spotify song is playing, in order to see what song is currently playing or just to know a song is still playing without noticing.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should show current Spotify song playing

### Tasks
- [ ] Add Spotify API
- [ ] Add Spotify player component
- [ ] Call the endpoint for given Spotify song playing.
- [ ] Show the current Song playing
