### ISSUE TITLE
Feature: Daily Temperature Plot

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#4]
### Description
As a HAP user, I'd like to get an overview of a graph with the temperature in my room for every 5 seconds, in order to calculate the average temperature per hour/day/week.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should show temperature in a plot
- [ ] Should refresh every 5 seconds
- [ ] Should give an average per hour/day/week

### Tasks
- [ ] _TBA_ Make a plot with Plotly.js
- [ ] _TBA_ Add the temperature to the plot for every 5 seconds
- [ ] _TBA_ Calculate the average per hour/day/week
