### ISSUE TITLE
Feature: Overview of lamps usage

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#5]
### Description
As a HAP user, I'd like to get an overview at what time of the day the lamps in my room are turned on/off, in order to get a sense of how much energy I'm using on average per day.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should show if lamps in my room are currently on/off
- [ ] Should give an overview of average energy usage per day

### Tasks
- [ ] _TBA_ Give back a status if lamps on my room are currently on/off
- [ ] _TBA_ Give the average usage per day
