### ISSUE TITLE
Feature: Consume message from back-end

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#7]
### Description
As a developer, I'd like to consume the message from the back end, in order to add the sensor data to the database

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should listen to sensor data updates
- [x] Should add sensor data to database

### Tasks
- [x] _TBA_ Get messages from queue
- [x] _TBA_ Add sensor data to database
