### ISSUE TITLE
Feature: AddRoom

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#8]
### Description
As a hap-user, I'd like to add a room to the dashboard, so I can keep the dashboard up to date with my rooms.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should open dialog on button click
- [ ] Should add room to database on button "add room" click

### Tasks

- [x] _TBA_ Create a category class containing an id and name
- [x] _TBA_ Create a database query to add rooms
- [x] _TBA_ Create POST endpoint to add a room by using create query
- [ ] _TBA_ Add a button with input which calls the POST endpoint when clicked
