### ISSUE TITLE
Feature: GetAllRooms

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S3-SiemLucassen-HAP#9]
### Description
As a hap-user, I'd like to retrieve all rooms to the dashboard, so I can show all rooms on the dashboard.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should Retrieve all rooms on page load of the Dashboard

### Tasks
- [x] _TBA_ Create a database query to get all rooms
- [x] _TBA_ Create a GET endpoint to get all rooms by using the get all query
- [ ] _TBA_ Create on page load event that fetches all rooms and shows a list of the room names
